openapi: 3.0.3
info:
  title: Exchange application
  version: 1.0.0
  description: |-
    This is a demo application which can calculate currency exchange for Polish Zloty's.
  contact:
    email: michalsu96@gmail.com
  #servers:
  #- url: TODO
tags:
  - name: currency
    description: All the endpoints related to currency exchange.
paths:
  /calculate-currency/{desiredCurrency}:
    get:
      tags:
        - currency
      summary: Calculates Polish Zloty's provided in request.
      description: Calculates Polish Zloty's according to given criteria.
      operationId: calculateCurrency
      parameters:
        - name: desiredCurrency
          in: path
          description: Desired currency code to which provided value should be exchanged in ISO 4217 standard.
          required: true
          schema:
            type: string
            maxLength: 3
            minLength: 3
            example: "CHF"
        - name: value
          in: query
          description: Value of currency to exchange in Polish Zloty.
          required: true
          schema:
            type: number
            example: 100.31
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ExchangeResultDTO'
        '404':
          description: Bad request
components:
  schemas:
    ExchangeResultDTO:
      type: object
      properties:
        currency:
          type: string
          maxLength: 3
          minLength: 3
          description: Currency of a value in ISO 4217 standard.
          example: "EUR"
        value:
          type: number
          description: Currency value.
          example: 104.13
        exchangeRate:
          $ref: '#/components/schemas/ExchangeRateDTO'
    ExchangeRateDTO:
      type: object
      properties:
        rate:
          type: number
          description: Exchange rate based on ask value.
          example: 4.2521
        date:
          type: string
          format: date
          description: Exchange rate date from which the calculation is performed.
          example: "2023-02-08"