openapi: 3.0.3
info:
  title: Exchange application
  version: 1.0.0
  description: |-
    This is a demo application which can calculate currency exchange for Polish Zloty's.
  contact:
    email: michalsu96@gmail.com
  #servers:
  #- url: TODO
tags:
  - name: currency
    description: All the endpoints related to currency exchange.
paths:
  /calculate-currency/{desiredCurrency}:
    get:
      tags:
        - currency
      summary: Calculates Polish Zloty's provided in request.
      description: Calculates Polish Zloty's according to given criteria.
      operationId: calculateCurrency
      parameters:
        - name: desiredCurrency
          in: path
          description: Desired currency code to which provided value should be exchanged in ISO 4217 standard.
          required: true
          schema:
            type: string
            maxLength: 3
            minLength: 3
            example: "CHF"
        - name: value
          in: query
          description: Value of currency to exchange in Polish Zloty.
          required: true
          schema:
            type: number
            example: 100.31
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ExchangeResultDTO'
        '400':
          $ref: '#/components/responses/BaseError'
        '404':
          $ref: '#/components/responses/BaseError'
components:
  schemas:
    ExchangeResultDTO:
      type: object
      description: Main object which holds the exchange result.
      properties:
        currency:
          type: string
          maxLength: 3
          minLength: 3
          description: Currency of a value in ISO 4217 standard.
          example: "EUR"
        value:
          type: number
          description: Currency value.
          example: 104.13
        exchangeRate:
          $ref: '#/components/schemas/ExchangeRateDTO'
    ExchangeRateDTO:
      type: object
      description: Details of the exchange rate for the exchange operation.
      properties:
        rate:
          type: number
          description: Exchange rate based on ask value.
          example: 4.2521
        date:
          type: string
          format: date
          description: Exchange rate date from which the calculation is performed.
          example: "2023-02-08"
    ErrorObject:
      type: object
      description: Main object which holds the data about the error.
      properties:
        timestamp:
          type: string
          format: date-time
          description: At which time the error occurs.
          example: "2017-07-21T17:32:28Z"
        status:
          type: integer
          description: Status of an error.
          example: 400
        type:
          type: string
          description: A type of an error.
          example: "incorrect_query_param"
        message:
          type: string
          description: Detailed message about the error.
          example: "Provided query parameter is invalid."
        details:
          type: array
          items:
            $ref: '#/components/schemas/ErrorDetails'
    ErrorDetails:
      type: object
      description: Object which holds the data about the error details.
      properties:
        type:
          type: string
          description: A type of an error.
          example: "param_criteria_is_not_met"
        message:
          type: string
          description: Detailed message about the error detail.
          example: "desiredCurrency parameter should be in ISO 4217 standard."
  responses:
    BaseError:
      description: Main object which holds the data about the error.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorObject'
            example:
              status: 400
              type: "incorrect_query_param"
              message: "Provided query parameter is invalid."